global:
  scrape_interval: 3s

  external_labels:
    monitor: "example-app"

rule_files:

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "app"

    static_configs:
      - targets: ["localhost:5000"]

  - job_name: "example"

    dns_sd_configs:
      - names: ["app"]
        port: 5000
        type: A
        refresh_interval: 5s
