apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 27017
    targetPort: 27017
  selector:
    name: mongo-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongo-db-deploy
  labels:
    name:  mongo-db
spec:
  selector:
    matchLabels:
      name: mongo-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  mongo-db
    spec:
      nodeSelector:
        "failure-domain.beta.kubernetes.io/zone": "eastus-2"
      containers:
      - image:  mongo
        name:  mongo-db-cntnr
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        ports:
        - containerPort:  27017
          name:  mongo-db
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-datadisk
        - mountPath: /data/configdb
          name: mongodb-configdisk
        imagePullPolicy: Always
      volumes:
        - name: mongodb-datadisk
          persistentVolumeClaim:
            claimName: mongodb-data-pvc
        - name: mongodb-configdisk
          persistentVolumeClaim:
            claimName: mongodb-config-pvc
      restartPolicy: Always